spring.application.name=egg-ai

openai.api.key=${OPENAI_API_KEY}

# For H2 Database (in-memory)
spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Specific Settings
spring.h2.console.enabled=true